title: Bikram Keshari Parida
logo: /assets/img/bkp_photo.png
description: Welcome to my page :)
        Within the domain of theoretical physics, my focal areas of investigation have centered on Koopman-von Neumann Mechanics and the intricacies of the Eisenhart lift technique. 
        In the realm of astrophysics, my research pursuits are concentrated upon modeling and conducting tidal deformation analyses of compact astrophysical objects, including Neutron
        Stars, Pulsars, Gravastars, Quark stars, and Active Galactic Nuclei (AGNs). Employing the general theory of relativity and modified gravity frameworks, I strive to decipher the
        enigmas and intricacies of these celestial phenomena. 

        My present doctoral research is at the confluence of artificial intelligence and computer vision, with a specific focus on 3D reconstruction from a single-view image. This niche
        area of research has the potential to redefine the frontiers of human perception and interaction with the digital world, providing an innovative dimension to my scientific endeavors.
        Of profound interest to me is the fusion of deep learning techniques with the realms of theoretical physics and astrophysics. I aspire to usher in novel solutions to intricate problems,
        thereby augmenting our comprehension of the universe and the complexities that underlie it.
        

show_downloads: false
theme: jekyll-theme-minimal
bio: your bio goes here!

