title: Bikram Keshari Parida
logo: /assets/img/bkp_photo.png
description: |
 Welcome to my page :) 

 I work in the fields of theoretical physics, Astrophysics, Artificial Intelligence, and Computer Vision.
 You can see my Research Gate ID in the link: https://www.researchgate.net/profile/Bikram-Parida-2
        

show_downloads: false
theme: jekyll-theme-minimal
bio: your bio goes here!

