title: Bikram Keshari Parida
logo: /assets/img/bkp_photo.png
description: Welcome to my page :) \n

        I am a Physics and AI researcher. I work in the fields of theoretical physics, Astrophysics, Artificial Intelligence, and Computer Vision.
        

show_downloads: false
theme: jekyll-theme-minimal
bio: your bio goes here!

